name: reviewdog
on: [pull_request]
jobs:
  textlint:
    name: textlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deps install
        run: yarn --frozen-lockfile 
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: lint
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn lint -f checkstyle | reviewdog -f=checkstyle -name=textlint -reporter=github-pr-review -level=warning
